### ISSUE TITLE
Unknown / Blank tag in browse by language pointing to Page not found

### ISSUE THREAD

**Issue by AnuragMohapatra** [deepsourcelabs/good-first-issue#97] opened 2020-08-09 11:49 UTC
Hi,

Under the Browse by language section, there is a tag with count 3 but nothing written in it,

![image](https://user-images.githubusercontent.com/8456793/89731405-1de35080-da8a-11ea-95e2-0b9f2eeb6cbf.png)

When you click on it, a 404 page not found response is thrown.

**Comment by dpuljic01** [comment] 2020-08-17 22:00
What should be expected behaviour?

**Comment by pnijhara** [comment] 2020-08-19 17:44
@dpuljic01 projects like:
- https://github.com/LappleApple/feedmereadmes
- https://github.com/neutraltone/awesome-stock-resources
- https://github.com/rust-lang/rust-by-example

are expected to show.

Why?
Because these repos are markdown based and GFI does not point out markdown as language.

@jaipradeesh what do you think?

**Comment by stfumehul** [comment] 2020-09-11 15:15
please assign this issue to me and provide some guidance, my first time

**Comment by shrutisatish00** [comment] 2020-10-10 07:12
@pnijhara shall I make a markdown tab with the aforementioned repos? (as part of hacktoberfest)

**Comment by pnijhara** [comment] 2020-10-10 07:25
@jai-deepsource @jaipradeesh can you look into this?

**Comment by ocean** [comment] 2020-10-16 08:27
I've added "Unknown" as a tag for these repos in PR #162 - not fully happy with it but these tags come from the GitHub API, so if GitHub doesn't know what language the repo is in, there's not really much to do but assign it to "Unknown". What does everyone think?

**Comment by sanket-deepsource** [comment] 2020-12-22 07:28
This has been fixed in a recent release. Thanks!

**Closed by sanket-deepsource** 2020-12-22 07:28 UTC
